# libs/media tests. They read the media generated by tests/fixtures/generate.sh, which `make test`
# runs first; GPU cases skip on machines without a Vulkan driver.
$(eval $(call oma_test,media_tests,$(wildcard tests/media/*.cpp),media gpu base))

FIXTURES_STAMP := tests/fixtures/generated/.stamp
$(FIXTURES_STAMP): tests/fixtures/generate.sh
	$(call say,GEN,tests/fixtures/generated)
	$(Q)tests/fixtures/generate.sh >/dev/null && touch $@
TEST_PREREQS += $(FIXTURES_STAMP)
